apiVersion: v1
kind: ConfigMap
metadata:
  name: currencyservice
data:
  PORT: "7000"
  DISABLE_PROFILER: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  labels:
    app: currencyservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currencyservice
      project: hipstershop
      tier: app
  template:
    metadata:
      labels:
        app: currencyservice
        project: hipstershop
        tier: app
    spec:
      containers:
        - name: currency
          image: srikanthhg/currencyservice:v1
          ports:
          - containerPort: 7000
          envFrom:
          - configMapRef:
              name: currencyservice
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
spec:
  type: ClusterIP # by default ClusterIP
  selector:
    app: currencyservice
    project: hipstershop
    tier: app
  ports:
  - protocol: TCP
    port: 7000 #service-port
    targetPort: 7000 #container-port